#!/bin/sh

export CM_VERBOSE=false

{ echo "Control.polyEqWarn := false;"
  echo "val _ = Control.MC.bindNonExhaustiveError := true;"
  echo "val _ = Control.MC.matchNonExhaustiveError := true;"
  echo "val _ = Control.MC.matchRedundantError := true;"

  for i do
    case $i in
      *.sml) echo 'use "'"$i"'";' ;;
      *.cm)  echo 'val _ = if CM.make "'"$i"'" handle _ => false then ()
                   else OS.Process.exit OS.Process.failure;' ;;
      *) echo "You can't have meant $i.  Maybe a CM file?" >&2 ; exit 1 ;;
    esac
  done
} | sml
